### PR TITLE
universal SQL script built out

### PR DESCRIPTION
**Pull request by ricky-bruner**
Pull Request to merge universal SQL script for team to use so that we all have working starter data.

Please pull down and review code for errors and testing.

### CODE REVIEW

**Review by thatmikeparrish — APPROVED** [review]
Looks good

**Comment by jeremiah3643** [comment]
Good! 👍

**Review by jeremiah3643 — APPROVED** [review]
👍

**Review by askingalot — CHANGES_REQUESTED** [review]
Please use the PR template.
https://github.com/spooky-oysters/bangazon-web-app/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by jeremiah3643** [comment]
### Link ###
---
https://github.com/NSS-Therapeutic-Raccoons/BangazonAPI/projects/1#card-14316547


### Proposed Changes ###
---
- Consolidated SQL Inserts into main SQL script.

### Steps to Test ###
---
```
git fetch --all
git checkout rbproduct
```
- Run SQL script from SQL folder in BangazonAPI solution directory.
- Check tables by to make sure all data has been inserted.

### Impacted Areas in Application ###
---
- Added data should not affect the application beyond adding new data to database.

### Mentions ###
---
@askingalot

**Review by askingalot — APPROVED** [review]
Looks good.

FYI you can reference an issue by just saying `#18` (as in #18)

**Pull request merged**
